export const LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";

export const SCROLL_POSTS_START = "SCROLL_POSTS_START";
export const SCROLL_POSTS_SUCCESS = "SCROLL_POSTS_SUCCESS";
export const SCROLL_POSTS_ERROR = "SCROLL_POSTS_ERROR";
